App\Entity\User:
    properties:
        plainPassword:
            - Regex: 
                pattern: '/^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[a-zA-Z]).{8,}$/'
                message: The password must contain at least 8 characters, one upper case character, one down case caracter and a digit
