App\Entity\User:
    properties:
        plainPassword:
            - Regex: 
                pattern: '/^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[a-zA-Z]).{8,}$/'
                message: The password must contain at least 8 characters, 1 uppercase character, 1 lowercase caracter and 1 digit
